version: '3'
services:
  postgres:
    image: "postgres:latest"
    container_name: db
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_user
      POSTGRES_DB: calendar
